-- SQL script to add Smart Camera fields to the reports table
-- This script adds AI-powered Smart Camera detection fields to support automated report generation

-- First, drop the view if it exists to avoid conflicts
DROP VIEW IF EXISTS smart_camera_statistics;

-- Add Smart Camera specific columns to reports table
ALTER TABLE reports
ADD COLUMN IF NOT EXISTS is_smart_camera_report BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS ai_confidence DECIMAL(3,2) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS smart_camera_capture_id TEXT DEFAULT NULL;

-- Ensure the ai_confidence column has the correct type (in case it was created with wrong type)
-- This will convert any existing data to DECIMAL
ALTER TABLE reports ALTER COLUMN ai_confidence TYPE DECIMAL(3,2) USING ai_confidence::DECIMAL(3,2);

-- Add index on Smart Camera reports for faster queries
CREATE INDEX IF NOT EXISTS idx_reports_smart_camera ON reports(is_smart_camera_report) WHERE is_smart_camera_report = TRUE;

-- Add index on AI confidence for analytics
CREATE INDEX IF NOT EXISTS idx_reports_ai_confidence ON reports(ai_confidence) WHERE ai_confidence IS NOT NULL;

-- Add index on Smart Camera capture ID for tracking
CREATE INDEX IF NOT EXISTS idx_reports_smart_camera_capture_id ON reports(smart_camera_capture_id) WHERE smart_camera_capture_id IS NOT NULL;

-- Add comments to document the new fields
COMMENT ON COLUMN reports.is_smart_camera_report IS 'Indicates if this report was automatically generated by the Smart Camera system';
COMMENT ON COLUMN reports.ai_confidence IS 'AI confidence score (0-1) for the automated detection that created this report';
COMMENT ON COLUMN reports.smart_camera_capture_id IS 'Unique identifier of the Smart Camera capture that generated this report';

-- Create a view for Smart Camera analytics
CREATE OR REPLACE VIEW smart_camera_statistics AS
SELECT
    COUNT(*) as total_smart_camera_reports,
    COUNT(CASE WHEN ai_confidence IS NOT NULL AND ai_confidence >= 0.9 THEN 1 END) as high_confidence_reports,
    COUNT(CASE WHEN ai_confidence IS NOT NULL AND ai_confidence >= 0.7 AND ai_confidence < 0.9 THEN 1 END) as medium_confidence_reports,
    COUNT(CASE WHEN ai_confidence IS NOT NULL AND ai_confidence < 0.7 THEN 1 END) as low_confidence_reports,
    AVG(CASE WHEN ai_confidence IS NOT NULL THEN ai_confidence END) as avg_confidence,
    MIN(CASE WHEN ai_confidence IS NOT NULL THEN ai_confidence END) as min_confidence,
    MAX(CASE WHEN ai_confidence IS NOT NULL THEN ai_confidence END) as max_confidence,
    ROUND(
        AVG(CASE WHEN ai_confidence IS NOT NULL THEN ai_confidence END) * 100, 2
    ) as avg_confidence_percentage
FROM reports
WHERE is_smart_camera_report = TRUE;

-- Create a function to get Smart Camera reports with analytics
CREATE OR REPLACE FUNCTION get_smart_camera_reports(
    limit_count INTEGER DEFAULT 50,
    offset_count INTEGER DEFAULT 0,
    min_confidence DECIMAL(3,2) DEFAULT 0.0
) RETURNS TABLE (
    report_id UUID,
    title TEXT,
    category TEXT,
    city TEXT,
    status TEXT,
    created_at TIMESTAMPTZ,
    ai_confidence DECIMAL(3,2),
    smart_camera_capture_id TEXT,
    proof_cid TEXT
) AS $$
BEGIN
    RETURN QUERY
    SELECT
        r.report_id,
        r.title,
        r.category,
        r.city,
        r.status,
        r.created_at,
        r.ai_confidence,
        r.smart_camera_capture_id,
        r.proof_cid
    FROM reports r
    WHERE r.is_smart_camera_report = TRUE
    AND (r.ai_confidence IS NULL OR r.ai_confidence >= min_confidence)
    ORDER BY r.created_at DESC
    LIMIT limit_count
    OFFSET offset_count;
END;
$$ LANGUAGE plpgsql;

-- Grant necessary permissions (adjust according to your RLS policies)
-- GRANT SELECT ON smart_camera_statistics TO authenticated;
-- GRANT EXECUTE ON FUNCTION get_smart_camera_reports TO authenticated;

-- Example query to check the new schema
-- SELECT column_name, data_type, is_nullable, column_default
-- FROM information_schema.columns
-- WHERE table_name = 'reports'
-- AND column_name IN ('is_smart_camera_report', 'ai_confidence', 'smart_camera_capture_id')
-- ORDER BY ordinal_position;